CREATE TABLE PRODUCT (
    PRODUCTID INT primary key,
    NAME varchar(20) not null,
    DESCRIPTION varchar not null,
    BASEPRICE DOUBLE not null,
    TAXRATE DOUBLE NOT NULL,
    PRODUCTSTATUS VARCHAR NOT NULL,
    INVENTORYQUANTITY INT NOT NULL
);
CREATE TABLE PRODUCTORDER (
    ID_ORDER INT PRIMARY KEY,
    NAME_ORDER VARCHAR (20) NOT NULL,
    ORDERSTATUS VARCHAR (20) NOT NULL,
    INVENTORYQUANTITY INT NOT NULL

);
ALTER TABLE PRDUCTORDER ADD FOREIGN KEY(INVENTORYQUANTITY)REFERENCES PRODUCT (ID_PRODUCT);